from __future__ import annotations

import hashlib
import os
import secrets
import stat
import tempfile
from pathlib import Path

from bctc_ai.core.hashing import sha256_bytes, sha256_file


class ContentStoreIntegrityError(RuntimeError):
    pass


def content_path(store_root: Path, digest: str, suffix: str) -> Path:
    if len(digest) != 64 or any(character not in "0123456789abcdef" for character in digest):
        raise ValueError("digest must be a lowercase SHA-256 hex string")
    safe_suffix = suffix.casefold() if suffix else ".bin"
    if not safe_suffix.startswith(".") or "/" in safe_suffix or "\\" in safe_suffix:
        raise ValueError("invalid content suffix")
    return store_root / "sha256" / digest[:2] / f"{digest}{safe_suffix}"


def materialize_immutable(source: Path, store_root: Path) -> tuple[Path, str]:
    source = source.resolve()
    digest = sha256_file(source)
    destination = content_path(store_root.resolve(), digest, source.suffix)
    destination.parent.mkdir(parents=True, exist_ok=True)
    if destination.exists():
        if sha256_file(destination) != digest:
            raise ContentStoreIntegrityError(f"existing content has wrong hash: {destination}")
        return destination, digest

    descriptor, temporary_name = tempfile.mkstemp(
        prefix=f".{destination.name}.", dir=destination.parent
    )
    temporary = Path(temporary_name)
    try:
        with source.open("rb") as input_stream, os.fdopen(descriptor, "wb") as output_stream:
            while chunk := input_stream.read(1024 * 1024):
                output_stream.write(chunk)
            output_stream.flush()
            os.fsync(output_stream.fileno())
        if sha256_file(temporary) != digest:
            raise ContentStoreIntegrityError(f"copy verification failed for {source}")
        try:
            os.link(temporary, destination)
        except FileExistsError:
            if sha256_file(destination) != digest:
                raise ContentStoreIntegrityError(
                    f"concurrent content has wrong hash: {destination}"
                ) from None
        destination.chmod(0o444)
        directory_fd = os.open(destination.parent, os.O_RDONLY)
        try:
            os.fsync(directory_fd)
        finally:
            os.close(directory_fd)
        return destination, digest
    finally:
        temporary.unlink(missing_ok=True)


def materialize_immutable_bytes(
    payload: bytes,
    store_root: Path,
    *,
    suffix: str,
) -> tuple[Path, str]:
    """Publish generated bytes into the concurrent, content-addressed store.

    The final name is derived solely from the bytes.  A hard-link publication
    makes concurrent equal writers harmless and prevents an existing object
    from being replaced.  Existing objects are always rehashed before reuse.
    """

    digest = sha256_bytes(payload)
    store_root = store_root.absolute()
    store_root.mkdir(parents=True, exist_ok=True)
    destination = content_path(store_root, digest, suffix)
    directory_flags = os.O_RDONLY
    if hasattr(os, "O_DIRECTORY"):
        directory_flags |= os.O_DIRECTORY
    if hasattr(os, "O_NOFOLLOW"):
        directory_flags |= os.O_NOFOLLOW
    hierarchy: list[tuple[Path, tuple[int, int]]] = []

    def open_directory(path: Path, parent_fd: int | None = None) -> int:
        name: str | Path = path if parent_fd is None else path.name
        try:
            descriptor = os.open(name, directory_flags, dir_fd=parent_fd)
        except FileNotFoundError:
            if parent_fd is None:
                raise
            try:
                os.mkdir(path.name, 0o755, dir_fd=parent_fd)
            except FileExistsError:
                pass
            descriptor = os.open(path.name, directory_flags, dir_fd=parent_fd)
        except OSError as error:
            raise ContentStoreIntegrityError(
                f"content hierarchy cannot be opened without following links: {path}"
            ) from error
        identity = os.fstat(descriptor)
        if not stat.S_ISDIR(identity.st_mode):
            os.close(descriptor)
            raise ContentStoreIntegrityError(f"content hierarchy is not a directory: {path}")
        hierarchy.append((path, (identity.st_dev, identity.st_ino)))
        return descriptor

    def validate_hierarchy() -> None:
        for path, expected_identity in hierarchy:
            observed = path.stat(follow_symlinks=False)
            if (
                stat.S_ISLNK(observed.st_mode)
                or (
                    observed.st_dev,
                    observed.st_ino,
                )
                != expected_identity
            ):
                raise ContentStoreIntegrityError(
                    "content-store hierarchy changed during publication"
                )

    root_fd = open_directory(store_root)
    sha_directory = store_root / "sha256"
    try:
        sha_fd = open_directory(sha_directory, root_fd)
    except BaseException:
        os.close(root_fd)
        raise
    shard_directory = sha_directory / digest[:2]
    try:
        directory_fd = open_directory(shard_directory, sha_fd)
    except BaseException:
        os.close(sha_fd)
        os.close(root_fd)
        raise
    temporary_name = f".{destination.name}.{secrets.token_hex(16)}.tmp"
    temporary_created = False
    temporary_identity: tuple[int, int] | None = None

    def hash_open_name(name: str) -> tuple[str, tuple[int, int, int]]:
        named_before = os.stat(name, dir_fd=directory_fd, follow_symlinks=False)
        if not stat.S_ISREG(named_before.st_mode):
            raise ContentStoreIntegrityError(f"content is not a regular file: {destination}")
        flags = os.O_RDONLY
        if hasattr(os, "O_NOFOLLOW"):
            flags |= os.O_NOFOLLOW
        descriptor = os.open(name, flags, dir_fd=directory_fd)
        try:
            identity = os.fstat(descriptor)
            if not stat.S_ISREG(identity.st_mode):
                raise ContentStoreIntegrityError(f"content is not a regular file: {destination}")
            hasher = hashlib.sha256()
            while block := os.read(descriptor, 1024 * 1024):
                hasher.update(block)
            named_after = os.stat(name, dir_fd=directory_fd, follow_symlinks=False)
            expected_identity = (identity.st_dev, identity.st_ino, identity.st_size)
            if (
                named_before.st_dev,
                named_before.st_ino,
                named_before.st_size,
            ) != expected_identity or (
                named_after.st_dev,
                named_after.st_ino,
                named_after.st_size,
            ) != expected_identity:
                raise ContentStoreIntegrityError("content name changed during verification")
            return hasher.hexdigest(), expected_identity
        finally:
            os.close(descriptor)

    try:
        try:
            existing = os.stat(destination.name, dir_fd=directory_fd, follow_symlinks=False)
        except FileNotFoundError:
            existing = None
        if existing is not None:
            existing_digest, existing_identity = hash_open_name(destination.name)
            if (
                not stat.S_ISREG(existing.st_mode)
                or stat.S_IMODE(existing.st_mode) != 0o444
                or (existing.st_dev, existing.st_ino, existing.st_size) != existing_identity
                or existing_digest != digest
            ):
                raise ContentStoreIntegrityError(f"existing content has wrong hash: {destination}")
            validate_hierarchy()
            return destination, digest

        flags = os.O_WRONLY | os.O_CREAT | os.O_EXCL
        if hasattr(os, "O_CLOEXEC"):
            flags |= os.O_CLOEXEC
        if hasattr(os, "O_NOFOLLOW"):
            flags |= os.O_NOFOLLOW
        descriptor = os.open(temporary_name, flags, 0o600, dir_fd=directory_fd)
        temporary_created = True
        temporary_stat = os.fstat(descriptor)
        temporary_identity = (temporary_stat.st_dev, temporary_stat.st_ino)
        with os.fdopen(descriptor, "wb") as stream:
            stream.write(payload)
            stream.flush()
            os.fsync(stream.fileno())
            os.fchmod(stream.fileno(), 0o444)
            os.fsync(stream.fileno())
        temporary_digest, _temporary_verified_identity = hash_open_name(temporary_name)
        if temporary_digest != digest:
            raise ContentStoreIntegrityError("generated content failed pre-publication hashing")
        try:
            os.link(
                temporary_name,
                destination.name,
                src_dir_fd=directory_fd,
                dst_dir_fd=directory_fd,
                follow_symlinks=False,
            )
        except FileExistsError:
            identity = os.stat(destination.name, dir_fd=directory_fd, follow_symlinks=False)
            concurrent_digest, concurrent_identity = hash_open_name(destination.name)
            if (
                not stat.S_ISREG(identity.st_mode)
                or stat.S_IMODE(identity.st_mode) != 0o444
                or (identity.st_dev, identity.st_ino, identity.st_size) != concurrent_identity
                or concurrent_digest != digest
            ):
                raise ContentStoreIntegrityError(
                    f"concurrent content has wrong hash: {destination}"
                ) from None
        os.fsync(directory_fd)
        published_stat = os.stat(destination.name, dir_fd=directory_fd, follow_symlinks=False)
        published_digest, published_identity = hash_open_name(destination.name)
        if (
            published_digest != digest
            or stat.S_IMODE(published_stat.st_mode) != 0o444
            or (
                published_stat.st_dev,
                published_stat.st_ino,
                published_stat.st_size,
            )
            != published_identity
        ):
            raise ContentStoreIntegrityError(
                f"published content failed verification: {destination}"
            )
        validate_hierarchy()
        return destination, digest
    finally:
        if temporary_created and temporary_identity is not None:
            try:
                observed = os.stat(temporary_name, dir_fd=directory_fd, follow_symlinks=False)
            except FileNotFoundError:
                observed = None
            if observed is not None and (observed.st_dev, observed.st_ino) == temporary_identity:
                os.unlink(temporary_name, dir_fd=directory_fd)
        os.close(directory_fd)
        os.close(sha_fd)
        os.close(root_fd)
